### ISSUE TITLE
添加的子分类都显示到导航栏里

### ISSUE THREAD

**Issue by unwenliu** [dingzd1995/typecho-theme-waxy#1]
分类，子分类都平铺在导航栏里，这样添加子分类的话导航栏太臃肿了，应该鼠标移动到父分类后显示子分类的下拉框吧

**Comment by dingzd1995** [comment]
目前有计划将导航栏和侧边栏的分类重写。我也发现这个问题了 =w=

**Comment by dingzd1995** [comment]
OK，目前导航栏的下拉菜单和自适应搜索框基本搞定。

后台设置页面
![2020-10-31_235222](https://user-images.githubusercontent.com/15831999/97783647-2bfdc480-1bd4-11eb-8688-08106cb1385d.png)

效果（这种情况很极端......）
![2020-10-31_235754](https://user-images.githubusercontent.com/15831999/97783830-2e145300-1bd5-11eb-8207-a170d25faff0.png)
