### ISSUE TITLE
github介绍图片无法显示

### ISSUE THREAD

**Issue by chuchenyl** [dingzd1995/typecho-theme-waxy#3]
无法显示，麻烦您修复一下

**Comment by dingzd1995** [comment]
经测试，我这正常显示。 

引用的图片是存放GitHub静态站点（[hexo.idzd.top](https://hexo.idzd.top/)）的资源，也就说一般情况下应该同步的。

但是，不排除抽风的情况。

近期，有重新写一下的想法，可能会换下图床。

如果您经常无法载入图片的话，可以考虑

1. 访问主站点：https://www.idzd.top/ （部署阿里云CDN，和自动切换的OSS/GitHub图床）
2. 访问测试站点：https://test.706x.com/ （可能访问失败）

**Comment by chuchenyl** [comment]
好的

**Comment by dingzd1995** [comment]
已更换图床~ d(*￣▽￣)=b
