### ISSUE TITLE
PC端插入视频问题

### ISSUE THREAD

**Issue by chuchenyl** [dingzd1995/typecho-theme-waxy#4]
1.PC端插入视频播放时无法拖动进度条
2.PC端播放视频有时边播放边转圈！
非常喜欢这个主题
希望能够不断完善

**Comment by dingzd1995** [comment]
已加入修复计划，正在复现问题。

如果您方便的话，可以提供相关的信息吗？

比如：视频地址，您的环境，插入视频时使用的具体代码。

**Comment by dingzd1995** [comment]
插入视频这个功能，实际上是使用原生H5实现的，也就是说，渲染，读取，解码，播放，完全依赖本地浏览器。

如果网络不好，或是本地浏览器不正常，均会发生此问题。
