### ISSUE TITLE
大佬，我的站开启https后页面错位了，css样式乱了

### ISSUE THREAD

**Issue by zhangyuchen813** [dingzd1995/typecho-theme-waxy#6]
我是新手，刚刚学会建站和blog，请问这个怎么处理啊？

**Comment by dingzd1995** [comment]
可以先尝试使用 ctrl + F5 强制刷新一下，看是不是本地缓存的问题。

一般情况下样式错位可能是部分文件没有获取全。

你可以按F12 打开控制台，切换到network （部分叫网络），然后刷新网页有404么？

还可以在主题设置那把cdn选项开成本地，防止第三份cdn挂了导致这个问题（bootscdn曾经挂过两天才恢复）

检查下typecho基本设置中网站地址是不是填错了？有的没有强制http跳转https，但是部分浏览器会拒绝协议混用。

如果，方便的话，可以提供网站相关的信息（地址，服务器，设置截图，问题截图）到dingzd1995@gmail.com。我会尽快回复的。

ps:最近有点忙，可能回复慢点

**Comment by zhangyuchen813** [comment]
搞定了 。3Q

Typecho程序设置
登录Typecho后台 -> 设置 -> 基本设置 -> 站点地址改成https的域名是必须的。

编辑Typecho站点根目录下的文件config.inc.php加入下面一行配置，否则网站后台还是会调用HTTP资源。

/** 开启HTTPS */
define('__TYPECHO_SECURE__',true);

**Comment by dingzd1995** [comment]
其实最好在Nginx上设置下 **http** 301重定向到 **https**，这样省很多事情。

`server {
     listen 80;
      server_name idzd.top www.idzd.top;    
      return 301 https://www.idzd.top$request_uri;
}`
![image](https://user-images.githubusercontent.com/15831999/102351498-81a1fb00-3fe1-11eb-8f34-6590410185aa.png)


但是，请注意，部分数据的提供者可能能仍然使用http，如果你让typecho强制走https可能会有问题（但是一般不支持https的网站很少了~）
