### ISSUE TITLE
请问如何关闭评论功能

### ISSUE THREAD

**Issue by TML233** [dingzd1995/typecho-theme-waxy#8]
因为没去公安备案申请那个交互式网站的凭证，所以评论这种交互式内容都不能搞（貌似）
所以得关闭全站评论功能，并且替换`前往评论`按钮

总之，很喜欢这个主题，感谢开发者！

**Comment by dingzd1995** [comment]
您好，关于评论这一部分是由typecho控制的，主题只负责展示。

您如果需要关闭评论的话有两种方案，

1.在编辑文章/独立页面时，选择 高级选项 > 权限控制 > 取消选中 **允许评论**

2.您需要找到主题目录下的**comments.php**文件，替换下图中红框位置的代码或是清空整个文件。

```php
<?php if (false): ?>
```

![image](https://user-images.githubusercontent.com/15831999/106357465-29307e00-6341-11eb-9e2c-2c33eedd9955.png)

![image](https://user-images.githubusercontent.com/15831999/106357528-8af0e800-6341-11eb-9691-83e869fca3e2.png)

**Comment by TML233** [comment]
谢谢！
